# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Peer Mac"
license = "Apache"
licenselink = "https://github.com/Peter-Mac/hugo-theme-petermac/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"
homepage = "https://github.com/Peter-Mac/hugo-theme-petermac"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "Peter Mac"
  homepage = "https://github.com/Peter-Mac"

# If porting an existing theme
[Original]
  name = "Huabing Zhao"
  homepage = "https://github.com/zhaohuabing"

